baseURL: https://aayush-khurana.netlify.app/
languageCode: en-us
title: Portfolio website for Aayush
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: Welcome to my website. Scroll down to learn more about my background and my recent projects in RStudio!
    title: Aayush Khurana's online portfolio
  blog: {}
  contact:
    address:
      - city: London, UK, NW1 4SA 
        country: United Kingdom
        street: Regent's Park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: aayushk.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: +44(0)7856115462
        title: Mobile
  custom_css: []
  custom_js: []
  description: "Your description"
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    #copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
       # label: Twitter
      #  url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/aayush.khurana.10/
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/aayush.khurana121/ 
      - icon: fa-github
        label: GitHub
        url: https://github.com/Aayush-Khurana
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/aayush-khurana
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About me
        url: blogs/about_me
      - name: Background  
        url: blogs/CV
      - name: Germany elections 2021
        url: blogs/Germany
      - name: Yield Curve Inversion
        url: blogs/Yield
      - name: Project Amsterdam
        url: blogs/Airbnb
      - name: King's Global Markets
        url: blogs/KGM
    menu: Menu
    subtitle: By Aayush
    title: My website
  tiles:
    enable: yes
    showcase:
      - image: About_me.jpg
        subtitle: A quick snapshot
        title: About Me 
        url: blogs/about_me
      - image: Workflow-Decor.jpg
        subtitle: Learn more about my professional side
        title: Background
        url: blogs/CV
      - image: German elections.jpg
        subtitle: Recreating the opinion polls graph for the 2021 German Elections
        title: Germany elections 2021
        url: blogs/Germany
      - image: Yield curve.jpg
        subtitle: Modelling the US yield curve
        title: Yield Curve Inversion
        url: blogs/Yield
      - image: Amsterdam.jpg
        subtitle: Incorporating Data wrangling and manipulation to create robust regression models
        title: Project Amsterdam
        url: blogs/Airbnb
      - image: KGM.jpg
        subtitle: A snapshot of my research for The London Financial as the Middle Eastern Equity Analyst
        title: King's Global Markets 
        url: blogs/KGM
  two:
    buttonText: Dive in
    enable: yes
    subtitle: "Learn more about my educational background, professional experiences and interest"
    title: Resume/CV
    url: blogs/CV
