---
categories:
- ""
- ""
date: "2017-10-31T22:42:51-05:00"
description: Find out a bit more about me
draft: false
keywords: ""
slug: about_me
title: A Brief Introduction
---


## A bit about me

```{r, echo=FALSE, fig.align='center', out.width='30%',out.extra='style="background-color: white;padding:10px"'}

library(knitr)


```


# Introduction
Hello I'm Aayush Khurana and I’m a student at LBS pursuing a Masters in Financial Analysis. Prior to joining LBS, I was at King's College London where I pursued my undergradate degree in Economics and Management. During my time at KCL, I was heavily involved in several societies namely -

1. **Enactus KCL as a Finance director** 
2. **King's Global Markets as a VP** 
3. **the Squash team representing the KCL Men's team in tournaments**. 

Previously, I have worked at *EY* as a business consultant and at *ING bank* as an equity research analyst. To further enhance my understanding of Finance, I also recently worked as a Corporate Finance analyst at a US based Fintech - [*EdgeConneX.*] (https://www.edgeconnex.com/)

## Aspirations
Given that our I am pursuing a 1 year masters, I am looking forward to making the most of my time at LBS. In particular, I aim to enhance my understanding of financial markets, participate in several clubs including the Finance and Squash clubs and most importantly meet and learn from people with diverse backgrounds. Post LBS, I hope to pursue a career in Capital Markets or Financial consultancy.


Below is a list of some of my favourite books. Although I don't get the time to read much these days, these books are still some of my favorites:

* When Breath Becomes Air
     * by Paul Kalanithi
* The Kite Runner
     * by Khaled Hosseini
* Three Cups of Tea
     * by Greg Mortenson and David Oliver Relin

Thank you for taking the time out to read a bit about me. 

>Feel free to reach out to me in the send message section of this website if you have any queries. 